### ISSUE TITLE
机场报错

### ISSUE THREAD

**Issue by xiaoxiaoxiaodeseyixia** [wd210010/just_for_happy#7]
Traceback (most recent call last):
  File "ikuuu.py", line 24, in <module>
    result = json.loads(html.text)['msg']
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by wd210010** [comment]
脚本没有问题 检查ck或者多运行几次

**Comment by xiaoxiaoxiaodeseyixia** [comment]
> 脚本没有问题 检查ck或者多运行几次
